SV_MAIN: Remove references to unused console variables.
sys_select_timeout: used in Windows mvdsv as parameter to NET_Sleep
sys_restart_on_error: used in Windows mvdsv to relaunch on error

Both variable settable but not used in 2.2 or 3.0